# Generated by Django 3.1.3 on 2021-08-09 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCBASIS', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='recommendation_of_course',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='courses',
            name='recommended_resources',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_competition', models.CharField(max_length=32)),
                ('competition_description', models.CharField(max_length=2000)),
                ('recommended_resources', models.CharField(default=None, max_length=2000)),
                ('recommendation_of_competition', models.CharField(default=None, max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('competition_category', models.CharField(max_length=50)),
                ('url_of_image', models.CharField(max_length=800)),
                ('viewable', models.BooleanField(blank=True, default=True, null=True)),
                ('editor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
