# Generated by Django 3.1.3 on 2021-08-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCBASIS', '0005_auto_20210811_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='recommendation_of_course',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='recommended_resources',
        ),
    ]
