# Generated by Django 3.1.3 on 2021-08-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCBASIS', '0003_auto_20210809_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='recommendation_of_course',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
