# Generated by Django 3.1.3 on 2021-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCBASIS', '0008_auto_20210815_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='recommendation_of_competition',
        ),
        migrations.RemoveField(
            model_name='competitions',
            name='recommended_resources',
        ),
        migrations.AddField(
            model_name='competitions',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='competition_description',
            field=models.FileField(upload_to='competition_guides'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.FileField(upload_to='course_guides'),
        ),
    ]
